### PR TITLE
Install Bootstrap 5

### PR DESCRIPTION
**Pull request by wdonray**
This is my first step in setting up my front-end stack, I already added Next.js and Typescript but that was in my first commit. This is my first pull request for the project and all I did was add Bootstrap 5.

### CODE REVIEW

**Review by chayboats — APPROVED** [review]
👍🏽

**Comment by devinbroussard** [comment]
👍🏽

**Comment by devinbroussard** [comment]
👍🏽

**Review by devinbroussard — APPROVED** [review]
👍🏽

**Pull request merged**
